fix/wp_theme_preview
vektor-inc/vk-css-optimize pull request #14
Opened 2023-08-15 05:25 UTC by shimotmk

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

## どういう変更をしたか？

* このプルリクで変更した事を記載してください

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

実装者が確認した手順を箇条書きで記載してください。

*
*
*

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

レビュワーがどういう手順で何を確認して欲しいかを記載してください。

*
*
*

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2023-08-18 09:01 UTC, mthaichi commented
@shimotmk 良いと思います。
PHPUnitについては、readme.mdに追記したほうがいいかなとおもいますが、あまり気にしないで、プルリク時にテストが通れば良いという感じでしょうか。
@kurudriveさんがよければ、マージしてリリースで良いかと。

2023-08-23 03:19 UTC, shimotmk commented
@mthaichi 
確認ありがとうございます🙇‍♂️

> @shimotmk 良いと思います。 PHPUnitについては、readme.mdに追記したほうがいいかなとおもいますが、あまり気にしないで、プルリク時にテストが通れば良いという感じでしょうか。 @kurudriveさんがよければ、マージしてリリースで良いかと。

readme.mdの扱いはよくわからなかったので何もしませんでした。

通常通り確認していただければと思います

2023-08-25 07:28 UTC, kurudrive requested changes

2023-08-25 07:28 UTC, kurudrive commented on tests/test-get_theme_template.php
> + * @package vk-blocks
```suggestion
 * @package vektor-inc/vk-css-optimize
```

2023-08-25 07:44 UTC, kurudrive approved these changes

2023-08-25 07:56 UTC, kurudrive commented
@shimotmk @mthaichi ありがとうございました。
バージョンだけ不具合修正のみなので 0.2.1 にしました。
普通にローカルでテスト通りましたのでマージしまっす！

2023-08-25 07:58 UTC, merged