【確認待ち】Deprecated: Use of "self" in callables is deprecated in VkCssOptimize.php on line 325 を修正
vektor-inc/vk-css-optimize pull request #16
Opened 2024-06-19 01:33 UTC by drill-lancer

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

Deprecated: Use of "self" in callables is deprecated in VkCssOptimize.php on line 325

## どういう変更をしたか？

Deprecated: Use of "self" in callables is deprecated in VkCssOptimize.php on line 325 を修正

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？
⇒ Deprecated を修正しただけなので省略

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

1. Tree Shaking を有効化
2. Deprecated: Use of "self" in callables is deprecated in VkCssOptimize.php on line 325 が出るのを確認
3. VK Blocks Pro の  composer.json の vektor-inc/vk-css-optimize のバージョンを dev-fix/deprecated-self-325 に変更
4. vendor フォルダと composer.lock を削除した状態で composer install
5. Deprecated: Use of "self" in callables is deprecated in VkCssOptimize.php on line 325 が消えているを確認
6. ページのソースを開いて Tree Shaking が効いているのを確認

## 確認URL

ローカル環境

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

1. Tree Shaking を有効化
2. Deprecated: Use of "self" in callables is deprecated in VkCssOptimize.php on line 325 が出るのを確認
3. VK Blocks Pro の  composer.json の vektor-inc/vk-css-optimize のバージョンを dev-fix/deprecated-self-325 に変更
4. vendor フォルダと composer.lock を削除した状態で composer install
5. Deprecated: Use of "self" in callables is deprecated in VkCssOptimize.php on line 325 が消えているを確認
6. ページのソースを開いて Tree Shaking が効いているのを確認

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2024-08-26 06:46 UTC, goutetsuguma commented
> Deprecated: Use of "self" in callables is deprecated in VkCssOptimize.php on line 325 が出るのを確認

こちらを確認しようと思いましたが、上記のエラーがわたしのローカル環境では確認できませんでした、、、
わたしの手順の問題の可能性もありますが、どなたか他の方ご確認いただけますか

2024-08-26 23:29 UTC, drill-lancer commented
@goutetsuguma 
PHP が 8.0 以上でないと発生しません。

2024-08-27 05:18 UTC, goutetsuguma commented
@drill-lancer 
テスト環境は PHP バージョン 8.2.9 でした。
すみません、vk-css-optimizeについてわたしがそもそも理解不足でして、、、
vk blocks proを developにして確認しておりますが、そもそも確認の仕方が違うのかもしれません、、

2024-08-27 07:32 UTC, drill-lancer commented
@goutetsuguma 
多分 wp-config.php のデバッグモードが発動していないとかでしょうか？

2024-08-28 01:15 UTC, goutetsuguma commented
ありがとうございます、デバックはtrueになっていました。
もしかすると私の環境の問題・確認の仕方がそもそも間違っているなどありそうですので、他の方で確認できましたらよろしくお願いします🙇

2024-09-11 01:17 UTC, goutetsuguma commented
ああ、、、すみませんよくよくみたら画面上にエラーメッセージを表示しないようにしていました、、、（`define('WP_DEBUG_DISPLAY', false);`）
確認します

2024-09-11 01:22 UTC, goutetsuguma commented
レビュワー確認方法で確認して、エラーが消えることを確認しました。Tree Shaking を有効でインラインで出力されていることを確認できました。

2人目確認待ち（で良いのかな？）にします

2024-09-25 09:42 UTC, kurudrive requested changes

2024-09-25 09:42 UTC, kurudrive commented on src/VkCssOptimize.php
> +			ob_start( array( VkCssOptimize::class, 'css_tree_shaking_buffer' ) );
```suggestion
			ob_start( array(  __CLASS__, 'css_tree_shaking_buffer' ) );
```
@drill-lancer これでよくね（・ｗ・？

2024-09-25 10:47 UTC, drill-lancer commented on src/VkCssOptimize.php
> +			ob_start( array( VkCssOptimize::class, 'css_tree_shaking_buffer' ) );
@kurudrive 
そうかも知れません。
AI に相談した結果上記の回答が得られたのですがどちらでも良いようです。

2024-09-25 10:49 UTC, merged